name: CI-curl-install

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run curl_install
        run: |
          pwd
          set -euo pipefail
          sh ./curl_install
