name: CI-macOS

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run macOS Setup Script
        run: |
          set -eo pipefail
          export TERM=xterm
          sudo bash setup_macOS
        shell: bash
      - name: Run General Script
        run: |
          ./install