name: CI-macOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run macOS Setup Script
        run: |
          set -euo pipefail
          export TERM=xterm-256color
          bash setup_macOS
        shell: bash
      - name: Run General Script
        run: |
          ./install