name: CI-ubuntu

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: |
      #     sudo apt-get update && sudo apt-get install -y sudo git
      - run: |
          pwd
      - run: |
          ./install