name: CI-ubuntu

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update && apt-get install -y sudo git
      - run: |
          git clone https://github.com/MarkHershey/dotfiles.git "$HOME"
      - run: |
          cd "${HOME}/dotfiles" && ./install