name: CI-ubuntu

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Ubuntu Setup Script
        run: |
          pwd
          set -eo pipefail
          export TERM=xterm
          ./setup_ubuntu